site_name: NeoPupil Documentation
site_url: ""
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
    primary: dark blue
    accent: deep purple
  
  # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light mode
    primary: blue
    accent: deep orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate

nav:
  - Overview: index.md
  - Setup: setup.md
  - GUI Navigation: GUI_navigation.md
  - API:
      - Code Documentation:
          - Overview: api/code_documentation.md
          - GUI.py: api/GUI_py.md
          - main_plots.py: api/main_plots_py.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences